title: Van
views:
  - theme: Backend-selected
    path: default_view
    title: Van
    icon: mdi:van-utility
    badges: []
    cards:
      - type: conditional
        conditions:
          - entity: binary_sensor.maxxfan_status
            state: 'off'
          - entity: binary_sensor.maxxfan_status
            state_not: 'on'
        card:
          type: entities
          entities:
            - entity: binary_sensor.maxxfan_status
              icon: mdi:wifi-off
              secondary_info: last-changed
              name: Disconnect time
          title: MaxxFan
      - type: conditional
        conditions:
          - entity: binary_sensor.maxxfan_status
            state: 'off'
          - entity: binary_sensor.maxxfan_status
            state_not: 'on'
        card:
          type: entities
          entities:
            - entity: binary_sensor.maxxfan_status
              icon: mdi:wifi-off
              secondary_info: last-changed
              name: Disconnect time
          title: Air conditioner
      - type: conditional
        conditions:
          - entity: binary_sensor.maxxfan_status
            state: 'on'
          - entity: binary_sensor.maxxfan_status
            state_not: 'off'
        card:
          type: entities
          show_header_toggle: false
          state_color: false
          title: MaxxFan
          entities:
            - card_type: horizontal-stack
              cards:
                - entity: switch.maxxfan_direction
                  name: Direction
                  template: maxxfan_buttons
                  type: custom:button-card
                  style: |
                    ha-card {
                      {% if is_state('fan.maxxfan_fan','off') %}
                        color: var(--disabled-text-color);
                        pointer-events: none;
                      {% endif %}
                    }
                  state:
                    - icon: mdi:rotate-left
                      name: Exhaust
                      value: 'on'
                    - icon: mdi:rotate-right
                      name: Intake
                      value: 'off'
                - entity: switch.maxxfan_cover
                  name: Cover
                  template: maxxfan_buttons
                  type: custom:button-card
                  state:
                    - icon: mdi:arrow-up
                      name: Open
                      value: 'on'
                    - icon: mdi:arrow-down
                      name: Closed
                      value: 'off'
                - entity: fan.maxxfan_fan
                  name: Power
                  template: maxxfan_buttons
                  type: custom:button-card
                  state:
                    - icon: mdi:fan
                      name: 'On'
                      value: 'on'
                    - icon: mdi:fan-off
                      name: 'Off'
                      value: 'off'
              type: custom:hui-element
            - type: custom:slider-entity-row
              entity: fan.maxxfan_fan
              min: 0
              max: 100
              step: 10
              hide_when_off: false
              name: Speed
              icon: none
              full_row: true
            - entity: sensor.maxxfan_temperature
              type: custom:multiple-entity-row
              state_header: Temperature
              name: Climate
              format: precision0
              entities:
                - entity: sensor.maxxfan_humidity
                  name: Humidity
                  styles:
                    width: 75px
                    text-align: center
            - entity: sensor.maxxfan_power
              type: custom:multiple-entity-row
              state_header: Power
              name: Electric
              secondary_info:
                entity: sensor.maxxfan_board_voltage
                name: 'ESP32:'
              entities:
                - entity: sensor.maxxfan_voltage
                  name: Voltage
                  styles:
                    width: 50px
                    text-align: center
                - entity: sensor.maxxfan_current
                  name: Current
                  styles:
                    width: 50px
                    text-align: center
            - entity: button.maxxfan_ir_synchronize
              name: Re-synchronize
              icon: mdi:remote
            - card_type: horizontal-stack
              cards:
                - type: custom:button-card
                  label: |
                    [[[
                      return "Uptime: " + states['sensor.uptime'].state
                    ]]]
                  name: |
                    [[[
                      var installed = states['update.maxxfan_firmware'].attributes.installed_version;
                      var latest = states['update.maxxfan_firmware'].attributes.latest_version;
                      if (installed == latest)
                        return "Firmware: Up-to-date";
                      else
                        return "Firmware: Version " + latest + " available";
                    ]]]
                  entity: update.maxxfan_firmware
                  entity_picture: /local/ESPHome icon.png
                  tap_action:
                    action: more-info
                  show_label: true
                  show_name: true
                  show_state: false
                  show_entity_picture: true
                  styles:
                    grid:
                      - grid-template-areas: '"i l" "i n"'
                      - grid-template-columns: 40px auto
                    icon:
                      - width: 24px
                    name:
                      - justify-self: start
                      - padding: 0px 0px 0px 15px
                      - font-size: 14px
                    label:
                      - justify-self: start
                      - font-size: 14px
                      - padding: 0px 0px 12px 15px
                    card:
                      - border: none
                      - height: 50px
                      - padding: none
                - type: custom:button-card
                  name: Restart
                  icon: mdi:restart
                  template: reset_button
                  entity: button.maxxfan_restart
                  tap_action:
                    action: call-service
                    service: button.press
                    service_data:
                      entity_id: button.maxxfan_restart
                  styles:
                    card:
                      - width: 100px
                      - height: 45px
              type: custom:hui-element
          card_mod:
            class: top-level-card
      - type: conditional
        conditions:
          - entity: binary_sensor.maxxfan_status
            state: 'on'
          - entity: binary_sensor.maxxfan_status
            state_not: 'off'
        card:
          type: entities
          show_header_toggle: false
          state_color: false
          title: Air Conditioner
          entities:
            - type: custom:thermostat-card
              entity: climate.maxxfan_air_conditioner
              no_card: true
              highlight_tap: true
              step: 1
              title: ''
              pending: 2
            - card_type: horizontal-stack
              cards:
                - type: custom:button-card
                  color_type: blank-card
                - type: custom:button-card
                  template: climate_fan_buttons
                  icon: mdi:fan-auto
                  tap_action:
                    action: call-service
                    service: climate.set_fan_mode
                    service_data:
                      entity_id: climate.maxxfan_air_conditioner
                      fan_mode: auto
                  styles:
                    icon:
                      - color: >
                          [[[ return
                          (states['climate.maxxfan_air_conditioner'].attributes.fan_mode
                          == 'auto') ? 'rgb(68,115,158)' :
                          'var(--disabled-text-color)';]]]
                - type: custom:button-card
                  template: climate_fan_buttons
                  icon: mdi:fan-speed-1
                  tap_action:
                    action: call-service
                    service: climate.set_fan_mode
                    service_data:
                      entity_id: climate.maxxfan_air_conditioner
                      fan_mode: low
                  styles:
                    icon:
                      - color: >
                          [[[ return
                          (states['climate.maxxfan_air_conditioner'].attributes.fan_mode
                          == 'low') ? 'rgb(68,115,158)' :
                          'var(--disabled-text-color)';]]]
                - type: custom:button-card
                  template: climate_fan_buttons
                  icon: mdi:fan-speed-2
                  tap_action:
                    action: call-service
                    service: climate.set_fan_mode
                    service_data:
                      entity_id: climate.maxxfan_air_conditioner
                      fan_mode: medium
                  styles:
                    icon:
                      - color: >
                          [[[ return
                          (states['climate.maxxfan_air_conditioner'].attributes.fan_mode
                          == 'medium') ? 'rgb(68,115,158)' :
                          'var(--disabled-text-color)';]]]
                - type: custom:button-card
                  template: climate_fan_buttons
                  icon: mdi:fan-speed-3
                  tap_action:
                    action: call-service
                    service: climate.set_fan_mode
                    service_data:
                      entity_id: climate.maxxfan_air_conditioner
                      fan_mode: high
                  styles:
                    icon:
                      - color: >
                          [[[ return
                          (states['climate.maxxfan_air_conditioner'].attributes.fan_mode
                          == 'high') ? 'rgb(68,115,158)' :
                          'var(--disabled-text-color)';]]]
                - type: custom:button-card
                  color_type: blank-card
              type: custom:hui-element
button_card_templates:
  maxxfan_buttons:
    color_type: icon
    color: rgb(68,115,158)
    hold_action:
      action: none
    show_label: false
    show_name: true
    show_state: false
    styles:
      grid:
        - grid-template-areas: '"n i"'
        - grid-template-rows: auto
        - grid-template-columns: auto
      icon:
        - width: 28px
      name:
        - justify-self: middle
        - align-self: middle
        - font-size: 14px
        - padding: 0px 0px
    tap_action:
      action: toggle
  reset_button:
    color_type: icon
    color: rgb(68,115,158)
    hold_action:
      action: none
    show_label: false
    show_name: true
    show_state: false
    styles:
      grid:
        - grid-template-areas: '"n i"'
        - grid-template-rows: auto
        - grid-template-columns: auto
      icon:
        - width: 28px
      name:
        - justify-self: middle
        - align-self: middle
        - font-size: 14px
        - padding: 0px 0px
  climate_fan_buttons:
    color_type: icon
    color: rgb(68,115,158)
    hold_action:
      action: none
    show_label: false
    show_name: false
    show_state: false
    styles:
      grid:
        - grid-template-areas: '"i"'
        - grid-template-rows: auto
        - grid-template-columns: auto
      icon:
        - width: 28px
      card:
        - border: none
        - width: 50px
